### PR TITLE
CI Test on scala/spark/delta matrix

### PR DESCRIPTION
**Pull request by brayanjuls**
This PR will guarantee that our library works for all versions scala/spark/delta version mentioned in the CI and also make it possible to perform this release, https://github.com/MrPowers/jodie/issues/67.

### CODE REVIEW

**Comment by brayanjuls** [comment]
@joydeepbroy-zeotap - could you please take a look at this CI? some changeDataFeed tests are failing for delta version 2.2.0.

**Comment by joydeepbroy-zeotap** [comment]
> @joydeepbroy-zeotap - could you please take a look at this CI? some changeDataFeed tests are failing for delta version 2.2.0.

yes @brayanjuls, just saw that. let me check once

**Comment by joydeepbroy-zeotap** [comment]
Hi, @brayanjuls I have raised a PR #71 for the issue caused by delta 2.2.0. It was a legitimate bug and I have tried to put an explainer on the PR itself. I was not sure how to take it up as this is a branch you have created. Feel free to take the changes and test in CI. Let me know your thoughts.

**Comment by brayanjuls** [comment]
LGTM now, @MrPowers can you take a look?

**Comment by MrPowers** [comment]
LGTM, thanks for adding this!

**Pull request merged**
