### PR TITLE
Hadoop filesystem operations

### PR DESCRIPTION
**Pull request by brayanjuls**
This is the first version of the operations still WIP because I need to add documentation and the configuration feature for authentication. It would be great if you can give me your feedback about the interfaces by looking at the unit test. 

This PR solves https://github.com/MrPowers/jodie/issues/1

### CODE REVIEW

**Comment by MrPowers** [comment]
@alfonsorr - can you take a look at this PR if you have a sec? https://github.com/MrPowers/jodie/pull/13

**Comment by MrPowers** [comment]
@brayanjuls - here's what I am seeing in the test suite:

* hio.remove.all(wd)
* hio.mkdir(wd / "dir1")
* hio.write(testFile, content)

These look elegant and consistent with the public interface of [os-lib](https://github.com/com-lihaoyi/os-lib) - definitely looks like you're on the right track!

**Comment by brayanjuls** [comment]
I am going to add the functions for copying and moving files and after that, I will wait for the review.

**Comment by MrPowers** [comment]
@brayanjuls - still the latest status that you'll add functions for copying/moving files and then I should review?  Let me know!

**Comment by brayanjuls** [comment]
@MrPowers - Yes, I haven't had the time to work on this last week, but I plan to finish it tomorrow night.

**Comment by MrPowers** [comment]
Awesome @brayanjuls, just let me know when it's ready!

**Comment by brayanjuls** [comment]
@MrPowers -  it can now be reviewed.

**Comment by MrPowers** [comment]
This is amazing work @brayanjuls.  I am going to start promoting this.

**Pull request merged**
