### PR TITLE
Registering a delta table to hive metastore.

### PR DESCRIPTION
**Pull request by brayanjuls**
This PR solves the issue: https://github.com/MrPowers/jodie/issues/15

### CODE REVIEW

**Comment by MrPowers** [comment]
Looks great!  It's possible that users would want to do this for Parquet tables as well.  Any way we can make this more generic, so it works for both Parquet and Delta tables?

**Comment by brayanjuls** [comment]
> Looks great! It's possible that users would want to do this for Parquet tables as well. Any way we can make this more generic, so it works for both Parquet and Delta tables?

I will add support for parquet table as well.

**Comment by MrPowers** [comment]
Can we use `DeltaTable.isDeltaTable`, to automatically infer when it's a Delta table?  That way the user only needs to explicitly supply `HiveHelpers.HiveProvider.PARQUET` when they're working with Parquet tables.  The user can still optionally explicitly specify `HiveProvider.DELTA`, but it'd be nice if this wasn't required.

**Comment by brayanjuls** [comment]
> Can we use `DeltaTable.isDeltaTable`, to automatically infer when it's a Delta table? That way the user only needs to explicitly supply `HiveHelpers.HiveProvider.PARQUET` when they're working with Parquet tables. The user can still optionally explicitly specify `HiveProvider.DELTA`, but it'd be nice if this wasn't required.

I think we already have that behavior implemented, by default the provider is HiveProvider.DELTA, so users using delta tables only need to call the function like this `HiveHelpers.registerTable(tableName,tablePath)` while user using parquet table needs to explicitly provide the provider like this `HiveHelpers.registerTable(tableName,tablePath,HiveProvider.PARQUET)`. Maybe I need to modify the documentation to make that clear there.

**Comment by MrPowers** [comment]
Thanks for clarifying @brayanjuls!

**Pull request merged**
